# Weights and biases
wandb_run: False

# Random seed
seed: None

# Directory structure
base_dir: ../FOPPL    # NOTE: This path should be relative to the daphne path
daphne_dir: ../daphne # NOTE: This path should be relative to the repository path

# Tests and programs to run
deterministic_tests: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
probabilistic_tests: [1, 2, 3, 4, 5, 6, 7, 8]
homework2_programs: []
homework3_programs: []
homework4_programs: []
TTV_programs: []

# Compilation
compile: False

# Evaluation method
#mode: desugar
mode: graph

# Inference method
#inference: None
inference: IS
#inference: MH
#inference: MHG
#inference: HMC
#inference: VI

# Inference stuff
num_samples: 1e3
num_samples_per_step: 1
num_steps: 1e2
learning_rate: 1e-1
tmax: 1e6 # Seconds
zero_b: True